name: Integración Continua Java
# ¿Cuándo se ejecuta esto?
on:
  push:
    # Para que lo haga en todas la ramas
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
# ¿Qué tareas va a realizar?
jobs:
  build:
    runs-on: ubuntu-latest # Máquina virtual donde se ejecutará
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v5
      - name: 2. Configurar el entorno de Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 3. Ejecutar tests con Maven Wrapper
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: |
          chmod +x mvnw
          ./mvnw test
